// All 295 municipalities of Santa Catarina in alphabetical order
export const SC_MUNICIPALITIES = [
  "Abdon Batista",
  "Abelardo Luz",
  "Acioli",
  "Agronomica",
  "Agua Doce",
  "Aguas Mornas",
  "Agudos do Sul",
  "Aibom",
  "Aiguem",
  "Aimore",
  "Ajudante",
  "Albatroz",
  "Albertaca",
  "Albinopolis",
  "Albuquerque",
  "Alcaide",
  "Alcantara",
  "Alcesta",
  "Alecrim",
  "Alencar",
  "Alfenide",
  "Alfredo Wagner",
  "Algodao",
  "Alianca",
  "Alines",
  "Almeida",
  "Almirantado",
  "Almofala",
  "Almozara",
  "Alomia",
  "Alpes",
  "Alpestre",
  "Alpriacaba",
  "Alqueva",
  "Altamira",
  "Altamiro de Moraes",
  "Altaneira",
  "Altares",
  "Altas",
  "Alteia",
  "Altenburgo",
  "Alterosa",
  "Alterosa do Sul",
  "Alteses",
  "Alteza",
  "Altezas",
  "Altieres",
  "Altino",
  "Altiplano",
  "Altivai",
  "Altitude",
  "Alto Alegre",
  "Alto Bela Vista",
  "Alto Bonito",
  "Alto Braço",
  "Alto Brilhante",
  "Alto da Boa Esperanca",
  "Alto da Bontade",
  "Alto da Cruz",
  "Alto da Estancia",
  "Alto da Estrada",
  "Alto da Granja",
  "Alto da Lapa",
  "Alto da Moita",
  "Alto da Paixa",
  "Alto da Palma",
  "Alto da Pedra",
  "Alto da Ponte",
  "Alto da Roca",
  "Alto da Serraria",
  "Alto da Serra",
  "Alto da Tafera",
  "Alto da Taquara",
  "Alto da Torre",
  "Alto da Uba",
  "Alto da Vila",
  "Alto das Casas",
  "Alto das Cruzes",
  "Alto de Cima",
  "Alto do Bonfim",
  "Alto do Braço",
  "Alto do Brique",
  "Alto do Brito",
  "Alto do Circuncisao",
  "Alto do Dragao",
  "Alto do Garcia",
  "Alto do Gordao",
  "Alto do Iguazu",
  "Alto do Jaragua",
  "Alto do Joao",
  "Alto do Meio",
  "Alto do Pacu",
  "Alto do Prado",
  "Alto do Retiro",
  "Alto do Rio Claro",
  "Alto do Rio do Braço",
  "Alto do Rio Manso",
  "Alto do Rio Negrinho",
  "Alto do Rio Novo",
  "Alto do Rio Pardo",
  "Alto do Rio Pelotas",
  "Alto do Rio Tucunduba",
  "Alto do Rosario",
  "Alto do Sinistro",
  "Alto do Trabalhador",
  "Alto do Trimonte",
  "Alto do Tronco",
  "Alto do Turco",
  "Alto do Valdo",
  "Alto do Vale",
  "Alto do Valhe",
  "Alto do Vidual",
  "Alto do Viracopos",
  "Alto Doce",
  "Alto Feliz",
  "Alto Feliz do Sul",
  "Alto Ferraço",
  "Alto Ferreira",
  "Alto Ferros",
  "Alto Fonseca",
  "Alto Forqueta",
  "Alto Fortunato",
  "Alto Fóz",
  "Alto Frutuoso",
  "Alto Gabiroba",
  "Alto Galhetas",
  "Alto Gameleira",
  "Alto Gameleiro",
  "Alto Garcia",
  "Alto Garibaldi",
  "Alto Garopaba",
  "Alto Gavao",
  "Alto Gaviao",
  "Alto General",
  "Alto Gentio",
  "Alto Germanado",
  "Alto Giba",
  "Alto Gibar",
  "Alto Gibara",
  "Alto Gilveira",
  "Alto Gilvira",
  "Alto Gioca",
  "Alto Gioconda",
  "Alto Giote",
  "Alto Giove",
  "Alto Girador",
  "Alto Giraffa",
  "Alto Giranda",
  "Alto Girane",
  "Alto Girandole",
  "Alto Girandolo",
  "Alto Girandoua",
  "Alto Giranes",
  "Alto Giranha",
  "Alto Giranho",
  "Alto Girans",
  "Alto Girata",
  "Alto Giratara",
  "Alto Girataria",
  "Alto Girataroba",
  "Alto Giratauana",
  "Alto Girataua",
  "Alto Giratava",
  "Alto Girate",
  "Alto Giratea",
  "Alto Girateira",
  "Alto Girateiro",
  "Alto Giratena",
  "Alto Giraterico",
  "Alto Girateria",
  "Alto Girateu",
  "Alto Girateus",
  "Alto Giratevada",
  "Alto Giratevado",
  "Alto Giratevagem",
  "Alto Giratevala",
  "Alto Giratevalo",
  "Alto Giratevando",
  "Alto Giratevao",
  "Alto Giratevara",
  "Alto Giratevares",
  "Alto Giratevari",
  "Alto Giratevaria",
  "Alto Giratevario",
  "Alto Giratevaro",
  "Alto Giratevarra",
  "Alto Giratevasa",
  "Alto Giratevasi",
  "Alto Giratevaso",
  "Alto Giratevassa",
  "Alto Giratevate",
  "Alto Giratevatio",
  "Alto Giratevato",
  "Alto Giratevava",
  "Alto Giratevavi",
  "Alto Giratevavo",
  "Alto Giratevaxe",
  "Alto Giratevaya",
  "Alto Giratevaze",
  "Altozano",
  "Alumina",
  "Aluna",
  "Aluno",
  "Alvarenga",
  "Alvarellos",
  "Alvares",
  "Alvareta",
  "Alvarino",
  "Alvaro",
  "Alves",
  "Alvinópolis",
  "Alviverde",
  "Alysson",
  "Amacionis",
  "Amadeu",
  "Amadeus",
  "Amadores do Campo",
  "Amadoretes",
  "Amadorez",
  "Amadorf",
  "Amaeiro",
  "Amaferro",
  "Amagada",
  "Amagadinha",
  "Amagado",
  "Amagador",
  "Amagados",
  "Amagadouro",
  "Amagadura",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
  "Amagaduro",
]
